[package]
name = "ovrcr-runtime"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
directories = { workspace = true }
libc = { workspace = true }
ovrcr-protocol = { workspace = true }
ovrcr-terminal = { workspace = true }
portable-pty = { workspace = true }
signal-hook = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
