[package]
name = "ovrcr-tui"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
libc = { workspace = true }
ovrcr-protocol = { workspace = true }
ovrcr-terminal = { workspace = true }
ratatui = { workspace = true }
signal-hook = { workspace = true }
