[[hooks.Interrupt]]

[[hooks.Interrupt.hooks]]
command = "exec '/Users/xlyk/Code/ovrcr/.worktrees/issue-58-ready-install/target/release/ovrcr' report codex --stdin"
type = "command"

[[hooks.SessionEnd]]

[[hooks.SessionEnd.hooks]]
command = "exec '/Users/xlyk/Code/ovrcr/.worktrees/issue-58-ready-install/target/release/ovrcr' report codex --stdin"
type = "command"

[[hooks.SessionStart]]
matcher = "startup|resume"

[[hooks.SessionStart.hooks]]
command = "exec '/Users/xlyk/Code/ovrcr/.worktrees/issue-58-ready-install/target/release/ovrcr' report codex --stdin"
type = "command"

[[hooks.Stop]]

[[hooks.Stop.hooks]]
command = "exec '/Users/xlyk/Code/ovrcr/.worktrees/issue-58-ready-install/target/release/ovrcr' report codex --stdin"
type = "command"

[[hooks.UserPromptSubmit]]

[[hooks.UserPromptSubmit.hooks]]
command = "exec '/Users/xlyk/Code/ovrcr/.worktrees/issue-58-ready-install/target/release/ovrcr' report codex --stdin"
type = "command"
